apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apigateway
    spec:
      containers:
      - image: 342003767516.dkr.ecr.us-east-1.amazonaws.com/api-repo:latest
        name: rabbitmq-microservices-kubernates-api-gateway-6djk9
        imagePullPolicy: IfNotPresent
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: eureka-client

