apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apigateway
  name: apigateway
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30543
  selector:
    app: apigateway
  type: NodePort
status:
  loadBalancer: {}
