apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: discovery-server
  name: discovery-server
spec:
  ports:
  - name: 8761-8761
    port: 8761
    targetPort: 8761
    nodePort: 30529
  selector:
    app: discovery-server
  type: NodePort
status:
  loadBalancer: {}
