apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: totalzus
  name: totalzus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: totalzus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: totalzus
    spec:
      containers:
      - image: rabbitmq-microservices-kubernates_total_zus
        name: rabbitmq-microservices-kubernates-total-zus-g8b6v
        resources: {}
        imagePullPolicy: IfNotPresent
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://discovery-server:8761/eureka
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            value: password
status: {}
