package com.acoustic.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.util.UUID;


@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "monthly_net")
@Builder
@Data
@Entity
public class MonthlyNet {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private BigDecimal amount;
    @DynamoDBAttribute
    private UUID uuid;

}
