apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "15672"
      port: 15672
      targetPort: 15672
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: rabbitmq
  type: NodePort
status:
  loadBalancer: {}
