apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: monthlygross
  name: monthlygross
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monthlygross
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monthlygross
    spec:
      containers:
      - image: rabbitmq-microservices-kubernates_monthly-gross
        name: rabbitmq-microservices-kubernates-monthly-gross-r9r8k
        imagePullPolicy: IfNotPresent
        resources: {}
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://discovery-server:8761/eureka
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            value: password
status: {}
