apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tax
  name: tax
spec:
  ports:
  - name: 8090-8090
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: tax
  type: LoadBalancer
status:

