apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tax
  name: tax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tax
    spec:
      containers:
      - image: 342003767516.dkr.ecr.us-east-1.amazonaws.com/tax-repo:latest
        name: rabbitmq-microservices-kubernates-tax-4jwrs
        imagePullPolicy: IfNotPresent
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: eureka-client

