apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: monthlynet
  name: monthlynet
spec:
  ports:
  - name: 8092-8092
    port: 8092
    protocol: TCP
    targetPort: 8092
  selector:
    app: monthlynet
  type: LoadBalancer
status:

