apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: health
  name: health
spec:
  ports:
  - name: 8088-8088
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: health
  type: LoadBalancer
status:
  loadBalancer: {}
