apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: health
  name: health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: health
    spec:
      containers:
      - image: rabbitmq-microservices-kubernates_health
        name: rabbitmq-microservices-kubernates-health-tfk68
        imagePullPolicy: IfNotPresent
        resources: {}
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: eureka-client
status: {}
