apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: health
  name: health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: health
    spec:
      containers:
      - image: rabbitmq-microservices-kubernates_health
        name: rabbitmq-microservices-kubernates-health-tfk68
        imagePullPolicy: IfNotPresent
        resources: {}
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://discovery-server:8761/eureka
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            value: password
status: {}
