apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: health
  name: health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: health
    spec:
      containers:
      - image: 342003767516.dkr.ecr.us-east-1.amazonaws.com/health-repo:latest
        name: rabbitmq-microservices-kubernates-health-tfk68
        imagePullPolicy: IfNotPresent
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: eureka-client

