package com.acoustic.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.math.BigDecimal;
@Getter
@Setter
@DynamoDBTable(tableName = "salary_calculator_orchestrator")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SalaryCalculatorOrchestratorData {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private BigDecimal grossMonthlySalary;

    @DynamoDBAttribute
    private String jobTitle;
}
