apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springadmin
  name: springadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springadmin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springadmin
    spec:
      containers:
      - image: 342003767516.dkr.ecr.us-east-1.amazonaws.com/adm-spring:latest
        name: rabbitmq-microservices-kubernates-spring-admin-69z26
        imagePullPolicy: IfNotPresent
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: eureka-client
          - name: SPRING.BOOT.ADMIN.UI.PUBLIC-URL
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: spring-admin
