apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springadmin
  name: springadmin
spec:
  ports:
  - name: 8099-8099
    port: 8099
    protocol: TCP
    targetPort: 8099
  selector:
    app: springadmin
  type: LoadBalancer
status:

