apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: annualnet
  name: annualnet
spec:
  ports:
  - name: 8093-8093
    port: 8093
    protocol: TCP
    targetPort: 8093
  selector:
    app: annualnet
  type: LoadBalancer
status:

